dist: bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.64.0/hugo_extended_0.64.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script: hugo

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: ouuan/ouuan.github.io
    target_branch: master
    email: y___o___u@126.com
    name: ouuan
